default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'voltz_partners') %>_development

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'voltz_partners') %>_test
